language: cpp
compiler:
  - gcc
  - clang
env:
  - CFLAGS=--coverage CXXFLAGS=--coverage
before_install:
  - sudo apt-get update
  - sudo apt-get install default-jdk libboost-dev libboost-filesystem-dev libgtest-dev swig
  - sudo pip install cpp-coveralls --use-mirrors
script:
  - cmake . -DWITH_CSHARP_FRONTEND=OFF -DWITH_JAVA_FRONTEND=ON -DWITH_PYTHON_FRONTEND=OFF -DBUILD_TESTS=ON
  - make -j4
  - ctest --output-on-failure .
after_success:
  - coveralls --exclude tests --exclude gtest-prefix --exclude CMakeFiles --exclude-pattern 'CMake[^\.]*\.c(?:pp)?' --exclude-pattern '[^\.]*\.h' > /dev/null
notifications:
  irc:
    channels:
      - "irc.freenode.org#gamelib"
    template:
      - "%{repository} (%{commit}) by %{author} : %{message} %{foo} "
      - "Build details: %{build_url}"
      - "Latest commit: %{compare_url}"
    on_success: change
    on_failure: change
    skip_join: true
