language: cpp
compiler:
  - gcc
  - clang
env:
  matrix:
    - BV=1.46
    - BV=1.48
    - BV=1.54
matrix:
  include:
    - compiler: gcc
      env: CFLAGS=--coverage CXXFLAGS=--coverage COVERAGE=1
      fast_finish: true
  exclude:
    - compiler: clang
      env: BV=1.48
    - compiler: clang
      env: BV=1.46
before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
install:
  - sudo apt-get install default-jdk libboost${BV}-dev libboost-filesystem${BV}-dev libboost-signals${BV}-dev libboost-system${BV}-dev libboost-test${BV}-dev libgtest-dev swig
  - if [ "$CXX" = "g++" -a "$BV" = "1.54" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" -a "$BV" = "1.54" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ -n "$COVERAGE" ]; then sudo pip install cpp-coveralls --use-mirrors; fi
script:
  - cmake . -DWITH_CSHARP_FRONTEND=OFF -DWITH_JAVA_FRONTEND=ON -DWITH_PYTHON_FRONTEND=OFF -DBUILD_TESTS=ON
  - make -j4
  - ctest --output-on-failure .
after_success:
  - if [ -n "$COVERAGE" ]; then coveralls --exclude tests --exclude gtest-prefix --exclude CMakeFiles --exclude-pattern 'CMake[^\.]*\.c(?:pp)?' --exclude-pattern '[^\.]*\.h' > /dev/null ; fi
notifications:
  irc:
    channels:
      - "irc.freenode.org#gamelib"
    template:
      - "%{repository} (%{commit}) by %{author} : %{message} %{foo} "
      - "Build details: %{build_url}"
      - "Latest commit: %{compare_url}"
    on_success: change
    on_failure: change
    skip_join: true
