set(HYPODERMIC_INSTALL_DIR ${CMAKE_EXTERNAL_BINARY_DIR}/hypodermic)

if(DEFINED CMAKE_TOOLCHAIN_FILE)
  set(CROSSCOMPILE_OPTIONS -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE})
endif()

ExternalProject_Add(
  hypodermic
  URL https://github.com/karolherbst/hypodermic/archive/master.zip
  CMAKE_ARGS ${CROSSCOMPILE_OPTIONS}
             -DCMAKE_INSTALL_PREFIX=${HYPODERMIC_INSTALL_DIR} -DBOOST_INCLUDEDIR=${Boost_INCLUDE_DIRS} -DBOOST_LIBRARYDIR=${Boost_LIBRARY_DIRS}
  BUILD_IN_SOURCE 0
)

if(MINGW)
  set(HYPODERMIC_LIBRARIES ${HYPODERMIC_INSTALL_DIR}/lib/libhypodermic.dll.a)
else()
  set(HYPODERMIC_LIBRARIES ${HYPODERMIC_INSTALL_DIR}/lib/libhypodermic.so)
endif()
set(HYPODERMIC_INCLUDE_DIRS ${HYPODERMIC_INSTALL_DIR}/include)
install_external_library(hypodermic ${HYPODERMIC_LIBRARIES})
install(DIRECTORY ${HYPODERMIC_INCLUDE_DIRS}/Hypodermic DESTINATION ${CMAKE_INSTALL_FULL_INCLUDEDIR})
